include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    implementation_imports: false

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_internal_member: ignore
    invalid_use_of_visible_for_testing_member: ignore
    invalid_use_of_protected_member: ignore
    only_throw_errors: ignore
    leading_newlines_in_multiline_strings: ignore
    parameter_assignments: ignore

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - prefer-match-file-name:
        exclude:
          - test/**
          - example/**
