name: riverpod_test
description: A testing library which makes it easy to test providers. Built to be used with the riverpod package.
version: 0.1.2
repository: https://github.com/Eronildo/riverpod_test

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.8.0
  riverpod: ^2.3.5
  test: ^1.24.2

dev_dependencies:
  lints: ^2.0.1
  mocktail: ^0.3.0

screenshots:
  - description: The riverpod test package logo.
    path: screenshots/logo.png
