name: riverpod_test
description: A testing library which makes it easy to test providers. Built to be used with the riverpod package.
version: 0.1.4
repository: https://github.com/Eronildo/riverpod_test
homepage: https://github.com/Eronildo/riverpod_test
topics: [test, tests, providers, riverpod, riverpod-test]

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.3.0
  riverpod: ^2.4.5
  test: ^1.24.3

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.1

screenshots:
  - description: The riverpod test package logo.
    path: screenshots/logo.png
