name: riverpod_test
description: A testing library which makes it easy to test providers. Built to be used with the riverpod package.
version: 0.1.0
repository: https://github.com/Eronildo/riverpod_test

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  diff_match_patch: ^0.4.1
  meta: ^1.8.0
  riverpod: ^2.3.5
  test: ^1.22.0

dev_dependencies:
  dart_code_metrics: ^5.7.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

screenshots:
  - description: The riverpod test package logo.
    path: screenshots/logo.png
